apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: openaihubs.openaihub.ibm.com
spec:
  group: openaihub.ibm.com
  names:
    kind: OpenAIHub
    listKind: OpenAIHubList
    plural: openaihubs
    singular: openaihub
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
