apiVersion: apps/v1
kind: Deployment
metadata:
  name: openaihub-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: openaihub-operator
  template:
    metadata:
      labels:
        name: openaihub-operator
    spec:
      serviceAccountName: openaihub-operator
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          # Replace this with the built image name
          image: ffdlops/openaihub:v0.0.3
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
        - name: operator
          # Replace this with the built image name
          image: ffdlops/openaihub:v0.0.3
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "openaihub-operator"
            - name: REACT_APP_API
              value: "169.63.38.242:32123"
      volumes:
        - name: runner
          emptyDir: {}
